name: Push to Chromatic

on: workflow_call

jobs:
  push_chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo "Chromatic |$TEST_SECRET|"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}