name: Push to Chromatic

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  # push_chromatic:
  #   runs-on: ubuntu-latest
  #   environment: chromatic
  #   steps:
  #     - name: Run
  #       run: echo "Chromatic secret |$TEST_SECRET| token |$TEST_TOKEN|"
  #       env:
  #         TEST_SECRET: ${{ secrets.TEST_SECRET }}
  #         TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
  
  on-success:
    runs-on: ubuntu-latest
    environment: chromatic
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          if-no-files-found: error

      - name: Print built output
        shell: bash
        run: |
          value=`cat test.txt`
          echo The result is $value

      - run: echo "Chromatic secret |$TEST_SECRET| token |$TEST_TOKEN|"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
