name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo "Test Run |$TEST_SECRET|"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
 