name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo "BUILT CONTENT" > test.txt
 
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if-no-files-found: error
        with:
          name: build-output
          path: test.txt